### ISSUE TITLE
Give a custom name to the analysis subfolder as well

### ISSUE THREAD

**Issue by matteobarbieri** [slipguru/palladio#10]
It could be useful to give a custom name to the analysis subfolder as well, so that if one has to share the results of multiple sessions does not have to manually rename all analysis folders.

Probably something like analysis_<SESSION_NAME> would be appropriate

**Comment by fdtomasi** [comment]
I agree.

I implemented the possibility to specify a unique name for the analysis folder via the `-o output_folder` when calling the `pd_analysis.py` script. The default remains 'analysis'.
