### ISSUE TITLE
Save data, labels, config parameters in a Bunch for analysis

### ISSUE THREAD

**Issue by fdtomasi** [slipguru/palladio#20]
This would simplify the analysis.

Also, more importantly, if in the config there is a random process to extract only a subset of samples, now the analysis reloads the config file, and it will use different samples w.r.t. the `run` part.

**Comment by matteobarbieri** [comment]
Done. There is now a classe for the configuration object which stores the input matrix and the label vector (along with other information such as feature names), without need to copy the actual data files for the analysis.
