### ISSUE TITLE
Plotting error in case of empty signature

### ISSUE THREAD

**Issue by matteobarbieri** [slipguru/palladio#8]
If for any reason the produced signature is empty, an error is raised in a plotting function.

How to reproduce this bug: simply set a high treshold (maybe higher than 1, for testing purposes), thus obtaining an empty signature (just check the `signature_regular.txt` file in the `analysis` subfolder) and then perform the analysis

**Comment by fdtomasi** [comment]
I think now the bug is resolved.
I had the same problem, I fix it with a check if, inside the loop for each estimator, the signature extracted by that particular estimator is non empty.

In this way, if no variable is selected, simply continue with the other estimators.
